---
title: "lec_1/11/18"
output: html_document
---
# Set-up
```{r}
library(tidyverse)
library(dplyr)
pred_prey <- read_delim("~/Desktop/Predator_and_prey_body_sizes_in_marine_food_webs_vsn4.txt", delim = "\t")
```

```{r}
pred_prey$test <- str_replace(pred_prey$latitude, "\xba", ".")
pred_prey$test
```

## Prelim analysis
```{r}
colnames(pred_prey) <- tolower(gsub(' ', '_', colnames(pred_prey)))

# Only adults and some columns of interest
adult_pred_food <- pred_prey %>% 
    mutate(predator_lifestage = tolower(predator_lifestage)) %>% # Mix of upper and lower case...
    filter(predator_lifestage == 'adult') %>% 
    select(predator_common_name, predator_length, prey_mass, predator_mass)

# Summarize data to plot
plot_data <- adult_pred_food %>% 
    group_by(predator_common_name) %>% 
    summarize(
        mean_pred_mass = mean(predator_mass),
        mean_prey_mass = mean(prey_mass),
        mean_pred_length = mean(predator_length)) %>% 
    filter(mean_pred_mass < 8000) # "outliers"

# Plot pred weight vs prey weight
ggplot(plot_data, aes(x = mean_pred_mass, y = mean_prey_mass)) +
    geom_point() +
    geom_smooth()

# Plot pred length vs prey weight
ggplot(plot_data, aes(x = mean_pred_length, y = mean_prey_mass)) +
    geom_point() +
    geom_smooth()
```

## Organizing
```{r}
colnames(pred_prey)
```

# Run From Here
```{r}
pred_prey_s <- pred_prey %>% 
  select(predator, prey, predator_mass, prey_mass, prey_mass_unit, geographic_location, mean_annual_temp, mean_pp, specific_habitat, latitude)

pred_prey_conv <- pred_prey_s %>% 
  mutate(prey_mass_conv = ifelse(.$prey_mass_unit == "mg", .$prey_mass * 1000, .$prey_mass))
```

## Finding ALL niches
```{r}
unique(pred_prey_conv$geographic_location)
```
```{r}
unique(pred_prey_conv$specific_habitat)
```
```{r}
pred_prey_conv %>% 
  select(geographic_location, specific_habitat) %>% 
  gather(geographic_location, specific_habitat) %>% 
  unique() 
```
```{r}
pred_prey_conv %>% 
  group_by(geographic_location, specific_habitat, predator, prey) %>% 
  summarise(mean_predator_mass = mean(predator_mass),
            mean_prey_mass = mean(prey_mass_conv))
```

```{r}
#write_csv(pred_prey_conv, "/Users/matthewlindsay/marine_data_converted.csv")
```

```{r}
data<- pred_prey_conv

prey_type_tally<- data %>% 
  select(predator, prey) %>% 
  group_by(predator, prey) %>% 
  tally()


collapsed_prey<- prey_type_tally %>% 
  select(prey) %>% 
  tally()


new<- data %>% 
  group_by(predator)
  

new<- collapsed_prey %>% 
  mutate(predatorclass = ifelse(n>1, "Generalist", "Specialist"))
new
# within each niche, is S or G more successful? proxy is mass, population. Using number of observations as a proxy for populaiton size, must acknoledge the faults with this
```

# Dealing with latitude
```{r}
#pred_prey_conv$latitude = gsub('<ba>', ' ', pred_prey_conv$latitude) %>% 
  View()
#pred_prey_conv$latitude = measurements::conv_unit(pred_prey_conv$latitude, from = 'deg_dec_min', to = 'dec_deg')
```

```{r}
#pred_prey_conv$test <- str_replace(pred_prey_conv$latitude, "<ba>", ".")
#View(pred_prey_conv)
```










