---
title: "Intial Analysis"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
data <- read_delim("pred_prey_data", delim = "\t")
```

```{r}
## Convert Latitude to numbers
data$NewLatitude <- str_replace(data$Latitude, "\xba", ".")

data$NewLatitude <- str_replace(data$NewLatitude, "'", "")

mutate(.data = data, Latposneg = 0)

data$Latposneg <- ifelse(substr(data$NewLatitude, start = 6, stop = 6) == "N", data$Latposneg <- 1, data$Latposneg <- -1)

head(data)

data$NewLatitude <- str_replace(data$NewLatitude, "N", "")
data$NewLatitude <- str_replace(data$NewLatitude, "S", "")
data$NewLatitude <- as.numeric(data$NewLatitude) * data$Latposneg

View(data)
```

```{r}
## Select columns of interest
data1 <- data %>% 
  mutate(prey_mass_conv = ifelse(.$`Prey mass unit` == "mg", .$`Prey mass` * 1000, .$`Prey mass`)) %>% 
  select(Predator, Prey, `Predator mass`, prey_mass_conv, `Type of feeding interaction`, `Geographic location`, `Specific habitat`, Depth, `Mean PP`, `Mean annual temp`, NewLatitude) %>% 
  mutate(Genus = stringr::word(Predator, 1))


write_csv(data1, "Finalized_Marine_Data.csv")
View(data1)
```

 ```{r}
## Count number of total observations and number of observations of individual genera within a niche
data2 <- data1 %>%   
 dplyr::group_by(`Geographic location`, `Specific habitat`) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  group_by(`Geographic location`, `Specific habitat`, Genus) %>% 
  mutate(N_genus = n()) %>% 
  ungroup()

View(data2)
```

```{r}
data3 <- data2 %>% 
  group_by(`Geographic location`, `Specific habitat`, Genus) %>% 
  mutate(Ratio = (N_genus / n)) %>% 
  summarize(Ratio = mean(Ratio), Total_genera = mean(n), N_genara = mean(N_genus)) %>% 
  filter(!Ratio == 1)

data3

```

 ```{r}
data4 <- data3 %>% 
dplyr::group_by(`Geographic location`, `Specific habitat`, Genus) %>% 
  tally() %>%
  tally()
  
data4
```

 ```{r}
data5 <- left_join(data3, data4, by = "Geographic location") 
data5 <- data5 %>% 
  select(-`Specific habitat.y`)
  
  
data5 <- data5 %>% 
  mutate(Null_ratio = (100 / n) / 100) %>% 
  mutate(Difference = Ratio - Null_ratio)


data5
  
```

 ```{r}
data5 %>% 
  ggplot(aes(x = "", y = Ratio, fill = `Genus`)) +  
  geom_bar(stat = "identity") + 
  coord_polar("y", start=0) + 
  facet_wrap(vars(`Geographic location`)) +
```


```{r}
head(data1)

fi1 <- data1 %>% 
 dplyr::group_by(`Geographic location`, `Specific habitat`) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  group_by(`Geographic location`, `Specific habitat`, `Type of feeding interaction`) %>% 
  mutate(N_fi = n()) %>% 
  ungroup() %>% 
  rename('FI' = `Type of feeding interaction`)

fi1
```

```{r}
fi2 <- fi1 %>% 
  group_by(`Geographic location`, `Specific habitat`, `Type of feeding interaction`) %>% 
  mutate(Ratio = (N_fi / n)) %>% 
  summarize(Ratio = mean(Ratio), Total_fi = mean(n), N_fi = mean(N_fi))

fi2
```

```{r}
fi3 <- fi2 %>% 
dplyr::group_by(`Geographic location`, `Specific habitat`, `Type of feeding interaction`) %>% 
  tally() %>%
  tally()
  
View(fi3)
```

```{r}
fi4 <- left_join(fi2, fi3, by = "Geographic location")

fi4

fi5 <- fi4 %>% 
  select(-`Specific habitat.y`) %>% 
  mutate(Null_ratio = (100 / nn) / 100) %>% 
  mutate(Difference = Ratio - Null_ratio)

fi5
```

```{r}
fi5 %>% 
  ggplot(aes(x = "", y = Ratio, fill = `Type of feeding interaction`)) +  
  geom_bar(stat = "identity") + 
  coord_polar("y", start=0) + 
  facet_wrap(vars(`Geographic location`))
  
```

```{r}
fi6 <- fi5 %>% 
  aggregate(Ratio ~ `Geographic location`, data = ., FUN = max)

fi7 <- left_join(fi5, fi6, by = "Geographic location")

fi7

fi8 <- fi7 %>% 
  filter(Ratio.x == Ratio.y) %>% 
  select(`Geographic location`, `Specific habitat.x`, `Type of feeding interaction`, `Ratio.x`)

fi8
```

```{r}
View(fi8)
```

```{r}
df_model <- data1 %>% 
  select(`Geographic location`, `Specific habitat`, `Depth`, `NewLatitude`, `Mean annual temp`, `Mean PP`) %>% 
  right_join(fi8, .) %>% 
  group_by(`Geographic location`, `Specific habitat.x`, `Type of feeding interaction`) %>% 
  summarize(Ratio = mean(Ratio.x), Mean_pp = mean(`Mean PP`), Mean_temp = mean(`Mean annual temp`), Depth = mean(Depth), Latitude = median(NewLatitude)) %>% 
  filter(!is.na(FI))

View(df_model)

```

```{r}
df_model %>% 
ggplot(aes(x = FI, y = Depth, color = FI)) +
  geom_boxplot() 
  ## facet_grid('`Geographic location`', scales = 'free_x')
```

```{r}
df_model %>% 
ggplot(aes(x = FI, y = Mean_pp, color = FI)) +
  geom_boxplot() 
 ## facet_grid('`Geographic location`', scales = 'free_x')
```

```{r}
df_model %>% 
ggplot(aes(x = FI, y = Mean_temp, color = FI)) +
  geom_boxplot()
  ##facet_grid('`Geographic location`', scales = 'free_x')
```

```{r}
df_model %>% 
ggplot(aes(x = FI, y = Latitude, color = FI)) +
  geom_boxplot()
  ##facet_grid('`Geographic location`', scales = 'free_x')
```



```{r}
library(lmerTest)
library(lme4)
```

```{r}
summary(df_model)
```


```{r}
fi_global <- data1 %>% 
  rename('FI' = `Type of feeding interaction`) %>% 
  select(FI, Depth, `Mean annual temp`, `Mean PP`, NewLatitude, `Geographic location`, `Specific habitat`) %>% 
  filter(NewLatitude > 0)

View(fi_global)

```

```{r}
fi_global %>% 
ggplot(aes(x = FI, y = NewLatitude, color = FI)) +
  geom_boxplot()
```

```{r}
fi_global %>% 
ggplot(aes(x = FI, y = Depth, color = FI)) +
  geom_boxplot()
```

```{r}
fi_global %>% 
ggplot(aes(x = FI, y = `Mean PP`, color = FI)) +
  geom_boxplot()
```

```{r}
fi_global %>% 
ggplot(aes(x = FI, y = `Mean annual temp`, color = FI)) +
  geom_boxplot()
```


```{r}
#FI_lm <- lm(FI ~ Depth, data = df_model, na.action = na.exclude)

#tukey_FI <- TukeyHSD(aov(FI ~ Depth, data = df_model))

TukeyHSD(aov(Depth ~ FI, data = fi_global))
TukeyHSD(aov(`Mean PP` ~ FI, data = fi_global))
TukeyHSD(aov(`Mean annual temp` ~ FI, data = fi_global))
TukeyHSD(aov(NewLatitude ~ FI, data = fi_global))

```

```{r}
summary(fi_global)
```


```{r}
fi_global_glm <- glm(FI ~ Depth, data = fi_global)
```

